# Build analytics

## Motivation

When building a project from source code to executables everything should go smoothly. This is not
always the case, a build can break for several reasons. This chapter will give an overview of
research done on build configurations and continuous integration.

<!--
 - Define build
 - Define context
 -->

## Research Questions

**RQ1** What is the current state of the art in the field of build analytics?
**RQ2** What is the current state of practice in the field of build analytics?
**RQ3** What future research can we expect in the field of build analytics?

## Search Strategy

Using the initial seed consisting of @bird2017predicting, @beller2017oops, @rausch2017empirical,
@beller2017travistorrent, @pinto2018work, @zhao2017impact, @widder2018m and @hilton2016usage we
used references to find new papers to analyze.

## Study Selection

Through this we found the following papers

## Summary of papers

### @bird2017predicting

_Initial Seed_

This is a US patent grant for a method of predicting software build errors. This patent is owned
by Microsoft. Using logistic regression a prediction can be made on the probability of a build
failing. Using this method build errors can be better anticipated, which decreases the time until
the build works again.

### @beller2017oops

_Initial Seed_

This paper explores data from Travis CI^[See https://travis-ci.org] on a large scale by analyzing
2,640,825 build logs of Java and Ruby builds. It uses <span
style="font-variant:small-caps">TravisTorrent</span> as a data source. It is found that the number
one reason for failing builds it test failure. It also explores differences in testing between
Java and Ruby.

### @rausch2017empirical

_Initial Seed_

A stuy on the build results of 14 open source software Java projects. It is similar to
@beller2017oops, albeit on a smaller scale. It does go more in depth on the result and changes
over time.

### @beller2017travistorrent

_Initial Seed_

This paper introduces <span style="font-variant:small-caps">TravisTorrent</span>, a dataset
containing analyzed builds from more than 1,000 projects. This data is freely downloadable from
the internet. It uses <span style="font-variant:small-caps">GHTorrent</span> to link the
information from travis to commits on GitHub.

### @pinto2018work

_Initial Seed_

This paper is a survey amongst Travis CI users. It found that users are not sure whether a job
failure represents a failure or not, that inadequate testing is the most common (technical) reason
for build breakage and that people feel that there is a false sense of confidence when blindly
trusing tests.

### @zhao2017impact

_Initial Seed_

<!-- Note: Interesting collab between Nanjing (China), Eindhoven (Netherlands), UC Davis (USA) and Carnegie Mellon (USA). -->

This paper analyzed approximately 160,000 projects written in seven different programming
languages. It notes that adoption of CI is often part of a reorganization. It collected
information on the differences before and after adoption of CI. There is also a survey amongst
developers to learn about their experiences in adopting Travis CI.

### @widder2018m

_Initial Seed_

This paper analyzes what factors have impact on abandonment of Travis. They find that increased
build complexity reduces the chance of abandonment, but larger projects abandon at a higher rate
and that a project's language has significant but varying effect. A surprising result is that
metrics of configuration attempts and knowledge dispersion in the project don't affect the rate of
abandonment.

### @hilton2016usage

_Initial Seed_

This paper explores which CI system developers use, how developers use CI and why developers use
CI. For this it analyzes data from Github, Travis CI and it conducts a developer survey. It finds
that projects using CI release twice as often, accept pull requests faster and have developers who
are less worried about breaking the build.

### @vassallo2017tale

_References @beller2017oops _

This paper discusses the difference in failures on continuous integration between open source
software (OSS) and industrial software projects. For this 349 Java OSS projects and 418 project
from ING Nederland, a financial organization.

Using cluser analysis it was observed that both kinds of projects share similar build failures,
but in other cases very different patterns emerge.

### @hassan2018hirebuild

_References @beller2017travistorrent _

This paper uses TravisTorrent (@beller2017travistorrent) to show that 22% of code commits include
changes in build script files to keep the build working or to fix the build.

In the paper a tool is proposed to automatically fix build failures based on previous changes.

### @vassallo2018break

_References @beller2017oops, @rausch2017empirical _

This paper proposes a tool called <span style="font-variant:small-caps">BART</span> to help
developers fix build errors. This tool eliminates the need to browse error logs which can be very
long by generating a summary of the failure with useful information.

### @zampetti2017open

_Referenced by @vassallo2018break _

This paper studies the usage of static analysis tools in 20 Java open source software projects
hosted on GitHub and using Travic CI as continuous integration infrastructure. There is
investigated which tools are being used, what types of issues make the build fail or raise
warnings and how is responded to broken builds. 

### @baltes2018no

_Google Scholar search term `Github "Continuous Integration"`, papers from 2018_

This paper analyses 93 GitHub projects before and after adoption of Travis CI. It finds only one
non-negligible effect, an increasing merge ratio, meaning that more merging commits in relation to
all commits after a project started using Travis CI. But the paper also shows that this effect can
be seen on projects not adopting CI. It shows the importance of having a proper dataset with as
little bias as possible.

## What is the current state of the art in the field of build analytics?

The current state-of-the-art in build analytics domain refers to the use of machine learning techniques
to increase the productivity when using Continuos Integration (CI), to generate contraints on the 
configuration of the CI that could improve build success rate and to predict build failures even for 
newer projects with less training data available. Beside the papers from the initial seed, we will discuss
the following state-of-the-art aproaches papers:

### @bisong2017built
This paper aims to find a balance between the frequency of integration and developers productivity. 
They proposed models able to predict the build time of a job taking advantage of data from TravisTorrent. 
Their research is also slighty addressing the problem of optimal build time. Their method consists of 
selecting using different strategies to select the relevant features from the 56 features presented in 
TravisTorrent build records and applying a set of both linear and non-linear algorithm for predicting 
the time of a build. They evaluate the models performance using Root Mean Square Error (RMSE) and R-Squared 
and obtained for some models like Extreme-Gradient-Boosting(XGBOOST) a very high R-Squared around 80%, which 
shows that their model was able to capture the variation of build time over multiple projects. The main downfall 
of this paper is the testing size of only 10000 records of the 1,846,396 available data due to computational 
limits resulted probably from the usage of R machine learning packages, instead of python with TensorFlow. 
Their research could be useful on one hand for software developers and project managers for a better time 
management scheme and one the other hand for other researchers that may improve their proposed models. 




### @santolucito2018statically


### @ni2018acona



## What is the current state of practice in the field of build analytics?

In this section, I will examine scientific papers to analyse the current trend of build analytics in the software development industry. 

### @fowler2006continuous

In this paper, Martin talks about the current state of the software industry in terms of Continuous Integration (CI) and comments on the practises required to implement CI effectively. He talks about his experience working for a large English electronics company where the development of a project took two years and the integration process took several months. Integration is a long and unpredictable process. Martin suggested this approach and that the two most common reactions he got were: “it can’t work (here)” or “doing it won’t make much difference”.  He expresses that most engineers don’t know how simple the process can be of setting the CI framework up. In this way, we get a glimpse into the practises popular within the industry regarding build analytics.

### @hilton2016usage

This paper examines the usage, costs and benefits of Continuous Integration. A survey conducted in open-source projects indicated that 40% of all projects used CI. Of the projects that used CI, 90% used Travis for their CI services. They also determine that the more popular projects use CI but there is no correlation between the popularity of language and usage of CI. It also observes that the median project introduces CI a year into development. The paper claims that CI is widely used in practise nowadays and CI adoption rates will increase even further in the future. 

### @rausch2017empirical

Version Control Systems (VCS) such as GitHub, and hosted build automation platforms such as Travis, have made Continuous Integration is widely available for projects of every size. This paper suggests that CI is widely used and has improved the quality of processes and developed software itself. However, the article suggests that there is little known about the variety and frequency of errors that cause builds to fail. It suggests that developers should eliminate flaky tests and address common issues regularly such as broken interaction with repositories to keep the build system healthy.

### @stolberg2009enabling

This paper defines CI as a key element in agile software development and testing environment. It also uses Marin Fowler’s practises of CI (as discussed previously) and expresses the importance of CI in the software industry.  

## What future research can we expect in the field of build analytics?

Future research in build analytics branches in a couple of different topics. @pinto2018work
proposes to focus on getting a better understanding of the users and why they might choose to
abandon an automatic build platform.

According to @baltes2018no future work could look into more perspectives when analyzing commit
data, for instance partitioning commits by developer. It also notes the importance of more
qualitative research.
