# App Store analytics

## API change and fault proneness: A threat to the success of Android apps
M. Linares-Vásquez, G. Bavota, C. Bernal-Cárdenas, M. Di Penta, R. Oliveto, and D. Poshyvanyk, in 
Proceedings of the 2013 9th joint meeting on foundations of software engineering, 2013, pp. 477–48
7.

The paper presents an empirical study that aims to corroborate the relationship between the fault- a
nd change-proneness of APIs and the degree of success of Android apps measured by their user ratings
. For this, the authors selected a sample of 7,097 free Android apps from the Google Play Market and
 gathered information of the changes and faults that the APIs used by them presented. Using this dat
a and statistical tools such as box-plots and the Mann-Whitney test, two main hypotheses were analyz
ed. The first hypothesis tested the relationship between fault-proneness (number of bugs fixed in th
e API) and the success of an app. The second tested the relationship between change-proneness (overa
ll method changes, changes in method signatures and changes to the set of exceptions thrown by metho
ds) and the success of an app. 
Finally, although no causal relationships between the variables can be assumed, the paper found sign
ificant differences of the level of success of the apps taking into consideration the change- and fa
ult-proneness of the APIs they use. 

## The Impact of API Change- and Fault-Proneness on the User Ratings of Android Apps
G. Bavota, M. Linares-Vásquez, C. E. Bernal-Cárdenas, M. D. Penta, R. Oliveto and D. Poshyvanyk, i
n IEEE Transactions on Software Engineering, vol. 41, no. 4, pp. 384-407, 1 April 2015.
doi: 10.1109/TSE.2014.2367027


The paper by Bavota et al. aims to find empirical evidence supporting the success of apps and the re
lationship with change- and fault-proneness of the underlying APIs, where the success of the app is 
measured by its user rating. They performed two case studies to find quantitative evidence using 584
8 free Android apps as well as an explanation for these results doing a survey with 45 professional 
Android developers. The quantitative case study was done by comparing the user ratings to the number
 of bug fixes and changes in the API that an app uses. They found that apps with a high user rating 
are significantly less change- and fault-prone than APIs used by apps with a low user rating. In the
 second case study the paper found that most of the 45 developers observed a direct relationship bet
ween the user ratings of apps and the APIs those apps use.

## How can i improve my app? Classifying user reviews for software maintenance and evolution
S. Panichella, A. D. Sorbo, E. Guzman, C. A. Visaggio, G. Canfora, and H. C. Gall, in 2015 ieee inte
rnational conference on software maintenance and evolution (icsme), 2015, pp. 281–290.

The most popular apps in the app stores (such as Google Play or App Store) receives thousands of use
r reviews per day and therefore it would be very time demanding to go through the reviews manually t
o obtain relevant information for the future development of the apps. This paper uses a combination 
of Natural Language Processing Sentiment Analysis and Text Analysis to extract relevant sentences fr
om the reviews and to classify them into the following categories: Information Seeking, Information 
Giving, Feature Request, Problem Discovery, and Others. The results show 75% precision and 74% recal
l when classifier (J48 using data from NLP+SA+TA) is trained on 20% of the data (1421 manually label
ed sentences from reviews of seven different apps) and the rest is used for testing. The paper also 
states that the results do not differ in a statistically significant manner when a different classif
ier is used and shows that precision and recall can be further improved by increasing the size of th
e data set.

