# Bug Prediction

## Motivation
Minimizing the number of bugs in software is an effort central to software engineering - faulty
code fails to fullfill the purpose it was written for, its impact ranges from sligthly
embarrassing to disastrous and dangerous, and last but not least - fixing it 
costs time and money. Resources in a 
software development lifecycle are almost always limited and therefore should be allocated to where
 they are needed most - in order to avoid bugs, they should be focused on the most fault-prone
 areas of the project. Being able to predict where such areas might be would allow more development and 
testing efforts to be allocated on the right places.

However, as noted in @DAmbros2012, reliably predicting which parts of source code are the most 
fault-prone is one of the holy-grails of software engineering. Thus it is not surprising that bug-prediction continues
 to garner a widespread research interest in software analytics, now equipped with the 
 ever-expanding toolbox of data-mining and machine learning techniques. In this survey we 
 investigate the current efforts in bug-prediction in the light of the advances in software analytics methods and focus our attention on answering the
  following research questions:

* **RQ1** What is the current state of the art in bug prediction?
More specifically, we aim to answer the following:
    * What software or other metrics does bug prediction rely on and how good are they?
    * What kind prediction models are predominantly used?
    * How are bug prediction models and results validated and evaluated?
* **RQ2** What is the current state of practice in bug prediction?
    * Are bug prediction techniques applied in practice and if so, how?
    * Are the current developments in the field able to provide actionable tools for developers?
* **RQ3** What are some of the open challenges and directions for future research?


## Research protocol
We started by studying the initial 6 seed papers which were selected based on domain knowledge:

* @Gyimothy2005
* @Catal2009review
* @Arisholm2010
* @DAmbros2010
* @Hall2012
* @Lewis2013

Our searches were based on the following elements:

1. Keyword search using search engines (Scopus, ACM Digital Library, IEEE Explorer).
The search query was constructed so that the paper title had to contain the phrase bug prediction,
 but also the other more general variants used in literature: *bug/defect/fault prediction*. 
The title also had to contain at least one of following keywords: *metrics*, *models*,
 *validation*, *evaluation*, *developers*. To remain within the bug prediction field we required
  *software* to appear in the abstract.

2. Filtering search results by publication date. We excluded papers older than 10 years; that is, published before 2008. 

3. Filtering by the number of citations. We selected papers with 10 or more citations in order to focus on the ones that already have some visibility within the field.

4. Exploring other impactful publications by the same authors.

## Answers

