# Build analytics

## Background

When building a project from source code to executables everything should go smoothly. This is not
always the case, a build can break for several reasons. This chapter will give an overview of
research done on build scripts and continuous integration.

<!--
 - Define build
 - Define context
 -->

## Research Questions

<!-- Subject to change -->

 * What are causes of a broken build?
 * With which goals is continuous integration applied?
 * What can be used to effectively fix a broken build?

## Search Strategy

Using the initial seed consisting of @bird2017predicting, @beller2017oops, @rausch2017empirical,
@beller2017travistorrent, @pinto2018work, @zhao2017impact, @widder2018m and @hilton2016usage we
used references and similar keywords to find new papers to analyze.

## Study Selection

Through this we found the following papers

## Summary of papers

### @bird2017predicting

This is a US patent grant for a method of predicting software build errors. This patent is owned
my Microsoft. Using logistic regression a prediction can be made on the probability of a build
failing. Using this method build errors can be better anticipated, which decreases the time until
the build works again.

### @vassallo2017tale

Discusses the difference in failures on continuous integration between open source software (OSS)
and industrial software projects. For this 349 Java OSS projects and 418 project from ING
Nederland, a financial organisation.

Using cluser analysis it was observed that both kinds of projects share similar build failures,
but in other cases very different patterns emerge.

### @hassan2018hirebuild

This paper uses TravisTorrent (@beller2017travistorrent) to show that 22% of code commits include
changes in build script files to keep the build working or to fix the build.

In the paper a tool is proposed to automatically fix build failures based on previous changes.

### @vassallo2018break

This paper proposes a tool called <span style="font-variant:small-caps">BART</span> to help
developers fix build errors. This tool eliminates the need to browse error logs which can be very
long by generating a summary of the failure with useful information.

### @zampetti2017open

This paper studies the usage of static analysis tools in 20 Java open source software projects
hosted on GitHub and using Travic CI as continuous integration infrastructure. There is
investigated which tools are being used, what types of issues make the build fail or raise
warnings and how is responded to broken builds. 
